///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Entity_Testing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ActivitiesValidation1 recording.
    /// </summary>
    [TestModule("155d823f-a195-4480-ad54-0afd43737ec0", ModuleType.Recording, 1)]
    public partial class ActivitiesValidation1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSMOKTEST.SMOKTEST_SKRepository repository.
        /// </summary>
        public static CCHSSMOKTEST.SMOKTEST_SKRepository repo = CCHSSMOKTEST.SMOKTEST_SKRepository.Instance;

        static ActivitiesValidation1 instance = new ActivitiesValidation1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ActivitiesValidation1()
        {
            VarEntity = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ActivitiesValidation1 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable VarEntity.
        /// </summary>
        [TestVariable("7215a04f-4236-4253-8129-a2533b8d323d")]
        public string VarEntity
        {
            get { return repo.VarEntity; }
            set { repo.VarEntity = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$VarEntity) on item 'LoginCCHSPortal.EntityLevel.NewOcean'.", repo.LoginCCHSPortal.EntityLevel.NewOceanInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.LoginCCHSPortal.EntityLevel.NewOceanInfo, "InnerText", VarEntity);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
