///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Entity_Testing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Programs recording.
    /// </summary>
    [TestModule("3d2cb227-309d-44a7-a168-3245842e84e5", ModuleType.Recording, 1)]
    public partial class Programs : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSMOKTEST.SMOKTEST_SKRepository repository.
        /// </summary>
        public static CCHSSMOKTEST.SMOKTEST_SKRepository repo = CCHSSMOKTEST.SMOKTEST_SKRepository.Instance;

        static Programs instance = new Programs();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Programs()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Programs Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Programs.Programs_Menu_Item' at 81;5.", repo.LoginCCHSPortal.Programs.Programs_Menu_ItemInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Programs.Programs_Menu_Item.Click("81;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Name' at 127;17.", repo.LoginCCHSPortal.Health_Trackers.NameInfo, new RecordItemIndex(2));
            repo.LoginCCHSPortal.Health_Trackers.Name.Click("127;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1Orgtest' with focus on 'LoginCCHSPortal.Health_Trackers.Name'.", repo.LoginCCHSPortal.Health_Trackers.NameInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Health_Trackers.Name.PressKeys("1Orgtest");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Search_Fn.Search_Button' at 27;26.", repo.LoginCCHSPortal.Member_Demographics.Search_Fn.Search_ButtonInfo, new RecordItemIndex(4));
            repo.LoginCCHSPortal.Member_Demographics.Search_Fn.Search_Button.Click("27;26");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
