///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Entity_Testing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Users recording.
    /// </summary>
    [TestModule("b11d8ba7-cd48-479e-a608-db13d3d0b28d", ModuleType.Recording, 1)]
    public partial class Users : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSMOKTEST.SMOKTEST_SKRepository repository.
        /// </summary>
        public static CCHSSMOKTEST.SMOKTEST_SKRepository repo = CCHSSMOKTEST.SMOKTEST_SKRepository.Instance;

        static Users instance = new Users();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Users()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Users Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Programs.Administration' at 58;8.", repo.LoginCCHSPortal.Programs.AdministrationInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Programs.Administration.Click("58;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Programs.Users' at 61;6.", repo.LoginCCHSPortal.Programs.UsersInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Programs.Users.Click("61;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName' at 359;7.", repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstNameInfo, new RecordItemIndex(2));
            repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName.Click("359;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Orgtest' with focus on 'LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName'.", repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstNameInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName.PressKeys("Orgtest");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Search_Fn.Search_Button' at 48;25.", repo.LoginCCHSPortal.Member_Demographics.Search_Fn.Search_ButtonInfo, new RecordItemIndex(4));
            repo.LoginCCHSPortal.Member_Demographics.Search_Fn.Search_Button.Click("48;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(5));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
