///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Entity_Testing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UseSearchValidation recording.
    /// </summary>
    [TestModule("bd0c3e94-c824-4952-a376-81f45370c180", ModuleType.Recording, 1)]
    public partial class UseSearchValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSMOKTEST.SMOKTEST_SKRepository repository.
        /// </summary>
        public static CCHSSMOKTEST.SMOKTEST_SKRepository repo = CCHSSMOKTEST.SMOKTEST_SKRepository.Instance;

        static UseSearchValidation instance = new UseSearchValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UseSearchValidation()
        {
            VarPlaceholder1 = "";
            VarEmail1 = "MyEmail";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UseSearchValidation Instance
        {
            get { return instance; }
        }

#region Variables

        string _VarPlaceholder1;

        /// <summary>
        /// Gets or sets the value of variable VarPlaceholder1.
        /// </summary>
        [TestVariable("2c1ed5ee-1208-4d3f-ac28-e000ce636121")]
        public string VarPlaceholder1
        {
            get { return _VarPlaceholder1; }
            set { _VarPlaceholder1 = value; }
        }

        string _VarEmail1;

        /// <summary>
        /// Gets or sets the value of variable VarEmail1.
        /// </summary>
        [TestVariable("e9631980-034b-4d65-987a-5e4b37c8d1b4")]
        public string VarEmail1
        {
            get { return _VarEmail1; }
            set { _VarEmail1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable rowNumber1.
        /// </summary>
        [TestVariable("944e56d7-9afe-4eaf-be0a-31ad0996f92b")]
        public string rowNumber1
        {
            get { return repo.rowNumber1; }
            set { repo.rowNumber1 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'LoginCCHSPortal.EntityLevel.UserEmailValidation' and assigning its value to variable 'VarPlaceholder1'.", repo.LoginCCHSPortal.EntityLevel.UserEmailValidationInfo, new RecordItemIndex(0));
            VarPlaceholder1 = repo.LoginCCHSPortal.EntityLevel.UserEmailValidation.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", VarPlaceholder1, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$VarEmail1) on item 'LoginCCHSPortal.EntityLevel.UserEmailValidation'.", repo.LoginCCHSPortal.EntityLevel.UserEmailValidationInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.LoginCCHSPortal.EntityLevel.UserEmailValidationInfo, "InnerText", VarEmail1);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
