///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Rewards
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DragRewards recording.
    /// </summary>
    [TestModule("434b81bd-eba3-494c-9e8e-d767dc0d9cbc", ModuleType.Recording, 1)]
    public partial class DragRewards : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static DragRewards instance = new DragRewards();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DragRewards()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DragRewards Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varRewardDragSource.
        /// </summary>
        [TestVariable("3aeb4daa-eab5-4e5c-92f2-85375a463220")]
        public string varRewardDragSource
        {
            get { return repo.varRewardDragSource; }
            set { repo.varRewardDragSource = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRewardDragDestination.
        /// </summary>
        [TestVariable("0750e76d-adb9-48d8-bab3-2ce3fbb2a007")]
        public string varRewardDragDestination
        {
            get { return repo.varRewardDragDestination; }
            set { repo.varRewardDragDestination = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'NewOceanAdminPortal.RewardGroupTemplates.NewReward' at 62;14.", repo.NewOceanAdminPortal.RewardGroupTemplates.NewRewardInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.RewardGroupTemplates.NewReward.MoveTo("62;14");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'NewOceanAdminPortal.RewardGroupTemplates.NewReward' at 70;6.", repo.NewOceanAdminPortal.RewardGroupTemplates.NewRewardInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.RewardGroupTemplates.NewReward.MoveTo("70;6", 1000);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'NewOceanAdminPortal.RewardGroupTemplates.DragRewardHere' at 62;14.", repo.NewOceanAdminPortal.RewardGroupTemplates.DragRewardHereInfo, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.RewardGroupTemplates.DragRewardHere.MoveTo("62;14");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
