///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Rewards
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MainTab2 recording.
    /// </summary>
    [TestModule("0de1d789-744e-4f77-8849-6eee6032596b", ModuleType.Recording, 1)]
    public partial class MainTab2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static MainTab2 instance = new MainTab2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MainTab2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MainTab2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ConfigureRewardMain.Frequency' at 35;4.", repo.NewOceanAdminPortal.ConfigureRewardMain.FrequencyInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.ConfigureRewardMain.Frequency.Click("35;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -2000 units.", new RecordItemIndex(1));
            Mouse.ScrollWheel(-2000);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.FrequencyCollapse.FormControl1' at 337;15.", repo.NewOceanAdminPortal.FrequencyCollapse.FormControl1Info, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.FrequencyCollapse.FormControl1.Click("337;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'NewOceanAdminPortal.FrequencyCollapse.FormControl1'.", repo.NewOceanAdminPortal.FrequencyCollapse.FormControl1Info, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.FrequencyCollapse.FormControl1.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.FrequencyCollapse.Text' at 181;15.", repo.NewOceanAdminPortal.FrequencyCollapse.TextInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.FrequencyCollapse.Text.Click("181;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'NewOceanAdminPortal.FrequencyCollapse.Text'.", repo.NewOceanAdminPortal.FrequencyCollapse.TextInfo, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.FrequencyCollapse.Text.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.FrequencyCollapse.Text1' at 62;13.", repo.NewOceanAdminPortal.FrequencyCollapse.Text1Info, new RecordItemIndex(6));
            repo.NewOceanAdminPortal.FrequencyCollapse.Text1.Click("62;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'NewOceanAdminPortal.FrequencyCollapse.Text1'.", repo.NewOceanAdminPortal.FrequencyCollapse.Text1Info, new RecordItemIndex(7));
            repo.NewOceanAdminPortal.FrequencyCollapse.Text1.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ConfigureRewardMain.Eligibility' at 37;9.", repo.NewOceanAdminPortal.ConfigureRewardMain.EligibilityInfo, new RecordItemIndex(8));
            repo.NewOceanAdminPortal.ConfigureRewardMain.Eligibility.Click("37;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -2000 units.", new RecordItemIndex(9));
            Mouse.ScrollWheel(-2000);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -2000 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(-2000);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ConfigureRewardMain.Reward' at 25;9.", repo.NewOceanAdminPortal.ConfigureRewardMain.RewardInfo, new RecordItemIndex(11));
            repo.NewOceanAdminPortal.ConfigureRewardMain.Reward.Click("25;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.RewardGroupTemplates.Text' at 58;16.", repo.NewOceanAdminPortal.RewardGroupTemplates.TextInfo, new RecordItemIndex(12));
            repo.NewOceanAdminPortal.RewardGroupTemplates.Text.Click("58;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'NewOceanAdminPortal.RewardGroupTemplates.Text'.", repo.NewOceanAdminPortal.RewardGroupTemplates.TextInfo, new RecordItemIndex(13));
            repo.NewOceanAdminPortal.RewardGroupTemplates.Text.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.RewardGroupTemplates.Text1' at 74;10.", repo.NewOceanAdminPortal.RewardGroupTemplates.Text1Info, new RecordItemIndex(14));
            repo.NewOceanAdminPortal.RewardGroupTemplates.Text1.Click("74;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'NewOceanAdminPortal.RewardGroupTemplates.Text1'.", repo.NewOceanAdminPortal.RewardGroupTemplates.Text1Info, new RecordItemIndex(15));
            repo.NewOceanAdminPortal.RewardGroupTemplates.Text1.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ConfigureRewardMain.IconIconGlobeIconLarge' at 8;2.", repo.NewOceanAdminPortal.ConfigureRewardMain.IconIconGlobeIconLargeInfo, new RecordItemIndex(16));
            repo.NewOceanAdminPortal.ConfigureRewardMain.IconIconGlobeIconLarge.Click("8;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_En' at 23;19.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EnInfo, new RecordItemIndex(17));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_En.Click("23;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_En'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EnInfo, new RecordItemIndex(18));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_En.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es' at 27;19.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EsInfo, new RecordItemIndex(19));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es.Click("27;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EsInfo, new RecordItemIndex(20));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ConfigureRewardMain.IconIconGlobeIconLarge' at 2;9.", repo.NewOceanAdminPortal.ConfigureRewardMain.IconIconGlobeIconLargeInfo, new RecordItemIndex(21));
            repo.NewOceanAdminPortal.ConfigureRewardMain.IconIconGlobeIconLarge.Click("2;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ConfigureRewardMain.Icon' at Center.", repo.NewOceanAdminPortal.ConfigureRewardMain.IconInfo, new RecordItemIndex(22));
            repo.NewOceanAdminPortal.ConfigureRewardMain.Icon.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}' with focus on 'NewOceanAdminPortal.ConfigureRewardMain.Icon'.", repo.NewOceanAdminPortal.ConfigureRewardMain.IconInfo, new RecordItemIndex(23));
            repo.NewOceanAdminPortal.ConfigureRewardMain.Icon.PressKeys("{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'NewOceanAdminPortal.ConfigureRewardMain.Icon'.", repo.NewOceanAdminPortal.ConfigureRewardMain.IconInfo, new RecordItemIndex(24));
            repo.NewOceanAdminPortal.ConfigureRewardMain.Icon.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ConfigureRewardMain.Icon1' at 209;15.", repo.NewOceanAdminPortal.ConfigureRewardMain.Icon1Info, new RecordItemIndex(25));
            repo.NewOceanAdminPortal.ConfigureRewardMain.Icon1.Click("209;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}' with focus on 'NewOceanAdminPortal.ConfigureRewardMain.Icon1'.", repo.NewOceanAdminPortal.ConfigureRewardMain.Icon1Info, new RecordItemIndex(26));
            repo.NewOceanAdminPortal.ConfigureRewardMain.Icon1.PressKeys("{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'NewOceanAdminPortal.ConfigureRewardMain.Icon1'.", repo.NewOceanAdminPortal.ConfigureRewardMain.Icon1Info, new RecordItemIndex(27));
            repo.NewOceanAdminPortal.ConfigureRewardMain.Icon1.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
