///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Programs.CarePlan
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditCareplan recording.
    /// </summary>
    [TestModule("c9ab6d34-9894-4c5f-940c-2a69b39c1ba2", ModuleType.Recording, 1)]
    public partial class EditCareplan : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSMOKTEST.SMOKTEST_SKRepository repository.
        /// </summary>
        public static CCHSSMOKTEST.SMOKTEST_SKRepository repo = CCHSSMOKTEST.SMOKTEST_SKRepository.Instance;

        static EditCareplan instance = new EditCareplan();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditCareplan()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditCareplan Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '324D5B' on item 'LoginCCHSPortal.HeaderColor'.", repo.LoginCCHSPortal.HeaderColorInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.HeaderColor.Element.SetAttributeValue("TagValue", "324D5B");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Every1WeekSOnSuMTu' at 106;7.", repo.LoginCCHSPortal.Forms.SomeDivTag.Every1WeekSOnSuMTuInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Every1WeekSOnSuMTu.Click("106;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Actions_on_Program_' at 318;11.", repo.LoginCCHSPortal.Actions_on_Program_Info, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Actions_on_Program_.Click("318;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Checkboxes' at 6;5.", repo.LoginCCHSPortal.CheckboxesInfo, new RecordItemIndex(4));
            repo.LoginCCHSPortal.Checkboxes.Click("6;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Close_button' at 18;7.", repo.LoginCCHSPortal.Close_buttonInfo, new RecordItemIndex(5));
            repo.LoginCCHSPortal.Close_button.Click("18;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.ModalClose_button' at 27;17.", repo.LoginCCHSPortal.ModalClose_buttonInfo, new RecordItemIndex(6));
            repo.LoginCCHSPortal.ModalClose_button.Click("27;17");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
