///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Programs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GlobeProgramTitleAndDescription recording.
    /// </summary>
    [TestModule("db478f4d-378e-4103-8bb5-b0745fc42818", ModuleType.Recording, 1)]
    public partial class GlobeProgramTitleAndDescription : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSMOKTEST.SMOKTEST_SKRepository repository.
        /// </summary>
        public static CCHSSMOKTEST.SMOKTEST_SKRepository repo = CCHSSMOKTEST.SMOKTEST_SKRepository.Instance;

        static GlobeProgramTitleAndDescription instance = new GlobeProgramTitleAndDescription();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GlobeProgramTitleAndDescription()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GlobeProgramTitleAndDescription Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Globle_Icon_Program_Title' at 5;11.", repo.LoginCCHSPortal.Forms.SomeDivTag.Globle_Icon_Program_TitleInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Globle_Icon_Program_Title.Click("5;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Title_English' at 37;32.", repo.LoginCCHSPortal.Health_Trackers.Title_EnglishInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Health_Trackers.Title_English.Click("37;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA Automation' with focus on 'LoginCCHSPortal.Health_Trackers.Title_English'.", repo.LoginCCHSPortal.Health_Trackers.Title_EnglishInfo, new RecordItemIndex(2));
            repo.LoginCCHSPortal.Health_Trackers.Title_English.PressKeys("QA Automation");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Title_Spanish' at 145;16.", repo.LoginCCHSPortal.Health_Trackers.Title_SpanishInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Health_Trackers.Title_Spanish.Click("145;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA Automation' with focus on 'LoginCCHSPortal.Health_Trackers.Title_Spanish'.", repo.LoginCCHSPortal.Health_Trackers.Title_SpanishInfo, new RecordItemIndex(4));
            repo.LoginCCHSPortal.Health_Trackers.Title_Spanish.PressKeys("QA Automation");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_Description' at 8;5.", repo.LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_DescriptionInfo, new RecordItemIndex(5));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_Description.Click("8;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA' with focus on 'LoginCCHSPortal.Health_Trackers.English_Description'.", repo.LoginCCHSPortal.Health_Trackers.English_DescriptionInfo, new RecordItemIndex(6));
            repo.LoginCCHSPortal.Health_Trackers.English_Description.PressKeys("QA");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Spanish_Description' at 61;26.", repo.LoginCCHSPortal.Health_Trackers.Spanish_DescriptionInfo, new RecordItemIndex(7));
            repo.LoginCCHSPortal.Health_Trackers.Spanish_Description.Click("61;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA' with focus on 'LoginCCHSPortal.Health_Trackers.Spanish_Description'.", repo.LoginCCHSPortal.Health_Trackers.Spanish_DescriptionInfo, new RecordItemIndex(8));
            repo.LoginCCHSPortal.Health_Trackers.Spanish_Description.PressKeys("QA");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_Description' at 7;7.", repo.LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_DescriptionInfo, new RecordItemIndex(9));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_Description.Click("7;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
