///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Programs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ProgramSearchByActive recording.
    /// </summary>
    [TestModule("04f4d115-76c4-4340-85de-666bcd4766d7", ModuleType.Recording, 1)]
    public partial class ProgramSearchByActive : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static ProgramSearchByActive instance = new ProgramSearchByActive();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ProgramSearchByActive()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ProgramSearchByActive Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Other.SelectAStatus' at 172;16.", repo.NewOceanAdminPortal.Other.SelectAStatusInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Other.SelectAStatus.Click("172;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '1' on item 'NewOceanAdminPortal.Other.SelectAStatus'.", repo.NewOceanAdminPortal.Other.SelectAStatusInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Other.SelectAStatus.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Member.SearchButton' at Center.", repo.NewOceanAdminPortal.Member.SearchButtonInfo, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.Member.SearchButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Active') on item 'NewOceanAdminPortal.Other.ProgramSearchResults'.", repo.NewOceanAdminPortal.Other.ProgramSearchResultsInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.NewOceanAdminPortal.Other.ProgramSearchResultsInfo, "InnerText", "Active");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Other.SelectAStatus' at 173;16.", repo.NewOceanAdminPortal.Other.SelectAStatusInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Other.SelectAStatus.Click("173;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Up}{Up}' with focus on 'NewOceanAdminPortal.Other.SelectAStatus'.", repo.NewOceanAdminPortal.Other.SelectAStatusInfo, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.Other.SelectAStatus.PressKeys("{Up}{Up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'NewOceanAdminPortal.Other.SelectAStatus'.", repo.NewOceanAdminPortal.Other.SelectAStatusInfo, new RecordItemIndex(6));
            repo.NewOceanAdminPortal.Other.SelectAStatus.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Member.SearchButton' at Center.", repo.NewOceanAdminPortal.Member.SearchButtonInfo, new RecordItemIndex(7));
            repo.NewOceanAdminPortal.Member.SearchButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
