///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Programs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchCarePlan recording.
    /// </summary>
    [TestModule("a53a0d43-26c2-49d5-a1ae-2470a45dde4b", ModuleType.Recording, 1)]
    public partial class SearchCarePlan : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSMOKTEST.SMOKTEST_SKRepository repository.
        /// </summary>
        public static CCHSSMOKTEST.SMOKTEST_SKRepository repo = CCHSSMOKTEST.SMOKTEST_SKRepository.Instance;

        static SearchCarePlan instance = new SearchCarePlan();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchCarePlan()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchCarePlan Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Programs.Programs_Menu_Item' at 61;13.", repo.LoginCCHSPortal.Programs.Programs_Menu_ItemInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Programs.Programs_Menu_Item.Click("61;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Name' at 113;16.", repo.LoginCCHSPortal.Health_Trackers.NameInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Health_Trackers.Name.Click("113;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA Automation' with focus on 'LoginCCHSPortal.Health_Trackers.Name'.", repo.LoginCCHSPortal.Health_Trackers.NameInfo, new RecordItemIndex(2));
            repo.LoginCCHSPortal.Health_Trackers.Name.PressKeys("QA Automation");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Member_Search_Results.Search_Button' at 53;24.", repo.LoginCCHSPortal.Member_Demographics.Member_Search_Results.Search_ButtonInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Member_Demographics.Member_Search_Results.Search_Button.Click("53;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LoginCCHSPortal.Forms.SomeDivTag.QAAutomation'.", repo.LoginCCHSPortal.Forms.SomeDivTag.QAAutomationInfo, new RecordItemIndex(4));
            Validate.Exists(repo.LoginCCHSPortal.Forms.SomeDivTag.QAAutomationInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
