///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Reward_Group_Template
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BadgeLabelandIcon recording.
    /// </summary>
    [TestModule("381ed6db-2c93-4d1d-a710-b4115de160bb", ModuleType.Recording, 1)]
    public partial class BadgeLabelandIcon : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static BadgeLabelandIcon instance = new BadgeLabelandIcon();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BadgeLabelandIcon()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BadgeLabelandIcon Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}{Return}'.", new RecordItemIndex(0));
            Keyboard.Press("{Tab}{Return}");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Content.IconIconGlobeIconLarge2' at 7;6.", repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge2Info, new RecordItemIndex(1));
            //repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge2.Click("7;6");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_En' at 29;16.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EnInfo, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_En.Click("29;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_En'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EnInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_En.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es' at 60;18.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EsInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es.Click("60;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EsInfo, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Content.IconIconGlobeIconLarge2' at 6;1.", repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge2Info, new RecordItemIndex(6));
            repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge2.Click("6;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(7));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -840 units.", new RecordItemIndex(8));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.RewardGroupTemplates.Badge_Icon' at Center.", repo.NewOceanAdminPortal.RewardGroupTemplates.Badge_IconInfo, new RecordItemIndex(9));
            repo.NewOceanAdminPortal.RewardGroupTemplates.Badge_Icon.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}' with focus on 'NewOceanAdminPortal.RewardGroupTemplates.Badge_Icon'.", repo.NewOceanAdminPortal.RewardGroupTemplates.Badge_IconInfo, new RecordItemIndex(10));
            repo.NewOceanAdminPortal.RewardGroupTemplates.Badge_Icon.PressKeys("{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'NewOceanAdminPortal.RewardGroupTemplates.Badge_Icon'.", repo.NewOceanAdminPortal.RewardGroupTemplates.Badge_IconInfo, new RecordItemIndex(11));
            repo.NewOceanAdminPortal.RewardGroupTemplates.Badge_Icon.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(12));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Content.DollarIcon' at 16;6.", repo.NewOceanAdminPortal.Content.DollarIconInfo, new RecordItemIndex(13));
            repo.NewOceanAdminPortal.Content.DollarIcon.Click("16;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Up}{Up}{Up}'.", new RecordItemIndex(14));
            Keyboard.Press("{Up}{Up}{Up}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
