///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Reward_Group_Template
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Bucket recording.
    /// </summary>
    [TestModule("069a1ac4-a37f-482a-a6bb-4745650d69ff", ModuleType.Recording, 1)]
    public partial class Bucket : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static Bucket instance = new Bucket();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Bucket()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Bucket Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.RewardGroupTemplates.Bucket' at 40;21.", repo.NewOceanAdminPortal.RewardGroupTemplates.BucketInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.RewardGroupTemplates.Bucket.Click("40;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Content.ButtonTagAddBucket' at 48;13.", repo.NewOceanAdminPortal.Content.ButtonTagAddBucketInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Content.ButtonTagAddBucket.Click("48;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Content.IconIconGlobeIconLarge3' at Center.", repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge3Info, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge3.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_En' at 58;18.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EnInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_En.Click("58;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Bucket 1' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_En'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EnInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_En.PressKeys("Bucket 1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es' at 48;23.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EsInfo, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es.Click("48;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EsInfo, new RecordItemIndex(6));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Content.IconIconGlobeIconLarge3' at Center.", repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge3Info, new RecordItemIndex(7));
            repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge3.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'activity_icon_bandage.png' on item 'NewOceanAdminPortal.Activities.ActivityIcon'.", repo.NewOceanAdminPortal.Activities.ActivityIconInfo, new RecordItemIndex(8));
            repo.NewOceanAdminPortal.Activities.ActivityIcon.Element.SetAttributeValue("TagValue", "activity_icon_bandage.png");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
