///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Reward_Group_Template
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DollarLabelIconDescription recording.
    /// </summary>
    [TestModule("a3d6ea1a-638a-4551-a436-eca1bac405ed", ModuleType.Recording, 1)]
    public partial class DollarLabelIconDescription : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static DollarLabelIconDescription instance = new DollarLabelIconDescription();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DollarLabelIconDescription()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DollarLabelIconDescription Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Content.IconIconGlobeIconLarge' at 5;5.", repo.NewOceanAdminPortal.Content.IconIconGlobeIconLargeInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge.Click("5;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_En' at Center.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EnInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_En.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_En'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EnInfo, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_En.PressKeys("Test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es' at Center.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EsInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_EsInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_1_Es.PressKeys("Test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Content.IconIconGlobeIconLarge' at 5;5.", repo.NewOceanAdminPortal.Content.IconIconGlobeIconLargeInfo, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.Content.IconIconGlobeIconLarge.Click("5;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'activity_icon_alcohol.png' on item 'NewOceanAdminPortal.Activities.ActivityIcon'.", repo.NewOceanAdminPortal.Activities.ActivityIconInfo, new RecordItemIndex(6));
            repo.NewOceanAdminPortal.Activities.ActivityIcon.Element.SetAttributeValue("TagValue", "activity_icon_alcohol.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.RewardGroupTemplates.IconIconGlobeIconLarge' at 5;5.", repo.NewOceanAdminPortal.RewardGroupTemplates.IconIconGlobeIconLargeInfo, new RecordItemIndex(7));
            repo.NewOceanAdminPortal.RewardGroupTemplates.IconIconGlobeIconLarge.Click("5;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_2_Es' at Center.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_2_EsInfo, new RecordItemIndex(8));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_2_Es.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_2_Es'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_2_EsInfo, new RecordItemIndex(9));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_2_Es.PressKeys("Test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.Globe_Text_Box_2_En' at Center.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_2_EnInfo, new RecordItemIndex(10));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_2_En.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test' with focus on 'NewOceanAdminPortal.Activities.Globe_Text_Box_2_En'.", repo.NewOceanAdminPortal.Activities.Globe_Text_Box_2_EnInfo, new RecordItemIndex(11));
            repo.NewOceanAdminPortal.Activities.Globe_Text_Box_2_En.PressKeys("Test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.RewardGroupTemplates.IconIconGlobeIconLarge' at 5;5.", repo.NewOceanAdminPortal.RewardGroupTemplates.IconIconGlobeIconLargeInfo, new RecordItemIndex(12));
            repo.NewOceanAdminPortal.RewardGroupTemplates.IconIconGlobeIconLarge.Click("5;5");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
