///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Login
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LaunchApplication recording.
    /// </summary>
    [TestModule("5cd65174-2163-48e5-a8dc-d08bc3999fa5", ModuleType.Recording, 1)]
    public partial class LaunchApplication : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static LaunchApplication instance = new LaunchApplication();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LaunchApplication()
        {
            BrowserType = "Chrome";
            varDomainName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LaunchApplication Instance
        {
            get { return instance; }
        }

#region Variables

        string _BrowserType;

        /// <summary>
        /// Gets or sets the value of variable BrowserType.
        /// </summary>
        [TestVariable("e0689827-3b0b-4e99-ae54-221469fc9955")]
        public string BrowserType
        {
            get { return _BrowserType; }
            set { _BrowserType = value; }
        }

        string _varDomainName;

        /// <summary>
        /// Gets or sets the value of variable varDomainName.
        /// </summary>
        [TestVariable("fec448cf-af06-417b-952f-9dc1acdf5876")]
        public string varDomainName
        {
            get { return _varDomainName; }
            set { _varDomainName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $varDomainName with browser specified by variable $BrowserType in maximized mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser(varDomainName, BrowserType, "", false, true, false, false, false);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
