///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.DragItems
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DragActivityAbAttack recording.
    /// </summary>
    [TestModule("7b290b08-673c-48b0-a766-eeb2689207ea", ModuleType.Recording, 1)]
    public partial class DragActivityAbAttack : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static DragActivityAbAttack instance = new DragActivityAbAttack();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DragActivityAbAttack()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DragActivityAbAttack Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Challenges.ActivityName' at 70;16.", repo.NewOceanAdminPortal.Challenges.ActivityNameInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Challenges.ActivityName.Click("70;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'a' with focus on 'NewOceanAdminPortal.Challenges.ActivityName'.", repo.NewOceanAdminPortal.Challenges.ActivityNameInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Challenges.ActivityName.PressKeys("a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'b' with focus on 'NewOceanAdminPortal.Challenges.ActivityName'.", repo.NewOceanAdminPortal.Challenges.ActivityNameInfo, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.Challenges.ActivityName.PressKeys("b");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'NewOceanAdminPortal.Challenges.AbAttackPA' at 66;11.", repo.NewOceanAdminPortal.Challenges.AbAttackPAInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Challenges.AbAttackPA.MoveTo("66;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'NewOceanAdminPortal.Challenges.AbAttackPA' at 74;3.", repo.NewOceanAdminPortal.Challenges.AbAttackPAInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Challenges.AbAttackPA.MoveTo("74;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'NewOceanAdminPortal.Other.DragHere' at 66;11.", repo.NewOceanAdminPortal.Other.DragHereInfo, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.Other.DragHere.MoveTo("66;11");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
