///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.DragItems
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DragStretchActivity recording.
    /// </summary>
    [TestModule("83cfe1b8-3c6e-444b-81a4-c2037245d14f", ModuleType.Recording, 1)]
    public partial class DragStretchActivity : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static DragStretchActivity instance = new DragStretchActivity();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DragStretchActivity()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DragStretchActivity Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Challenges.ActivityName' at 70;16.", repo.NewOceanAdminPortal.Challenges.ActivityNameInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Challenges.ActivityName.Click("70;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'morning s' with focus on 'NewOceanAdminPortal.Challenges.ActivityName'.", repo.NewOceanAdminPortal.Challenges.ActivityNameInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Challenges.ActivityName.PressKeys("morning s");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 6s.", new RecordItemIndex(2));
            Delay.Duration(6000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'NewOceanAdminPortal.Programs.MorningStretchPA' at 37;12.", repo.NewOceanAdminPortal.Programs.MorningStretchPAInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Programs.MorningStretchPA.MoveTo("37;12");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'NewOceanAdminPortal.Programs.MorningStretchPA' at 45;4.", repo.NewOceanAdminPortal.Programs.MorningStretchPAInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Programs.MorningStretchPA.MoveTo("45;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'NewOceanAdminPortal.Content.DragAnItemOrClickHereToConfigure' at 37;12.", repo.NewOceanAdminPortal.Content.DragAnItemOrClickHereToConfigureInfo, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.Content.DragAnItemOrClickHereToConfigure.MoveTo("37;12");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
