///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Home_Page
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The HomePageNavigations recording.
    /// </summary>
    [TestModule("3be1e818-c008-40b3-b5bb-b3c9297b59a7", ModuleType.Recording, 1)]
    public partial class HomePageNavigations : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static HomePageNavigations instance = new HomePageNavigations();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public HomePageNavigations()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static HomePageNavigations Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 8s.", new RecordItemIndex(0));
            Delay.Duration(8000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Home.FirstMemberName_HomeScreen' at Center.", repo.NewOceanAdminPortal.Home.FirstMemberName_HomeScreenInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Home.FirstMemberName_HomeScreen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=' Member Name (required):') on item 'NewOceanAdminPortal.Home.Demographics'.", repo.NewOceanAdminPortal.Home.DemographicsInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.NewOceanAdminPortal.Home.DemographicsInfo, "InnerText", " Member Name (required):");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Home.Home' at Center.", repo.NewOceanAdminPortal.Home.HomeInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Home.Home.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Home.FirstDOB_HomeScreen' at Center.", repo.NewOceanAdminPortal.Home.FirstDOB_HomeScreenInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Home.FirstDOB_HomeScreen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=' Member Name (required):') on item 'NewOceanAdminPortal.Home.Demographics'.", repo.NewOceanAdminPortal.Home.DemographicsInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.NewOceanAdminPortal.Home.DemographicsInfo, "InnerText", " Member Name (required):");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
