///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Reset_Password
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ActivateAccount recording.
    /// </summary>
    [TestModule("454bf063-e84a-4999-83a2-5de74aed5467", ModuleType.Recording, 1)]
    public partial class ActivateAccount : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static ActivateAccount instance = new ActivateAccount();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ActivateAccount()
        {
            varVerificationCode = "yourtext";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ActivateAccount Instance
        {
            get { return instance; }
        }

#region Variables

        string _varVerificationCode;

        /// <summary>
        /// Gets or sets the value of variable varVerificationCode.
        /// </summary>
        [TestVariable("150ef56c-308d-4b38-aeed-e2541c1e1de4")]
        public string varVerificationCode
        {
            get { return _varVerificationCode; }
            set { _varVerificationCode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ActivateAccount' at 246;17.", repo.NewOceanAdminPortal.ActivateAccountInfo, new RecordItemIndex(0));
            //repo.NewOceanAdminPortal.ActivateAccount.Click("246;17");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            //Delay.Duration(2000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Login.Email' at 27;19.", repo.NewOceanAdminPortal.Login.EmailInfo, new RecordItemIndex(2));
            //repo.NewOceanAdminPortal.Login.Email.Click("27;19");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'usertest@cchs.com' with focus on 'NewOceanAdminPortal.Login.Email'.", repo.NewOceanAdminPortal.Login.EmailInfo, new RecordItemIndex(3));
            //repo.NewOceanAdminPortal.Login.Email.PressKeys("usertest@cchs.com");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Login.ContinueButton' at 133;19.", repo.NewOceanAdminPortal.Login.ContinueButtonInfo, new RecordItemIndex(4));
            //repo.NewOceanAdminPortal.Login.ContinueButton.Click("133;19");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(5));
            //Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Reset_Password.Code' at 38;21.", repo.NewOceanAdminPortal.Reset_Password.CodeInfo, new RecordItemIndex(6));
            repo.NewOceanAdminPortal.Reset_Password.Code.Click("38;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varVerificationCode' with focus on 'NewOceanAdminPortal.Reset_Password.Code'.", repo.NewOceanAdminPortal.Reset_Password.CodeInfo, new RecordItemIndex(7));
            repo.NewOceanAdminPortal.Reset_Password.Code.PressKeys(varVerificationCode);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'What is the name of the street where you grew up?' on item 'NewOceanAdminPortal.SystemComObject.TheSecurityQuestionIsRequired'.", repo.NewOceanAdminPortal.SystemComObject.TheSecurityQuestionIsRequiredInfo, new RecordItemIndex(8));
            repo.NewOceanAdminPortal.SystemComObject.TheSecurityQuestionIsRequired.Element.SetAttributeValue("TagValue", "What is the name of the street where you grew up?");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Reset_Password.Answer' at 37;22.", repo.NewOceanAdminPortal.Reset_Password.AnswerInfo, new RecordItemIndex(9));
            repo.NewOceanAdminPortal.Reset_Password.Answer.Click("37;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'front street' with focus on 'NewOceanAdminPortal.Reset_Password.Answer'.", repo.NewOceanAdminPortal.Reset_Password.AnswerInfo, new RecordItemIndex(10));
            repo.NewOceanAdminPortal.Reset_Password.Answer.PressKeys("front street");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Reset_Password.NewPassword' at 36;21.", repo.NewOceanAdminPortal.Reset_Password.NewPasswordInfo, new RecordItemIndex(11));
            repo.NewOceanAdminPortal.Reset_Password.NewPassword.Click("36;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Password1' with focus on 'NewOceanAdminPortal.Reset_Password.NewPassword'.", repo.NewOceanAdminPortal.Reset_Password.NewPasswordInfo, new RecordItemIndex(12));
            repo.NewOceanAdminPortal.Reset_Password.NewPassword.PressKeys("Password1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Reset_Password.ConfirmNewPassword' at 45;22.", repo.NewOceanAdminPortal.Reset_Password.ConfirmNewPasswordInfo, new RecordItemIndex(13));
            repo.NewOceanAdminPortal.Reset_Password.ConfirmNewPassword.Click("45;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Password1' with focus on 'NewOceanAdminPortal.Reset_Password.ConfirmNewPassword'.", repo.NewOceanAdminPortal.Reset_Password.ConfirmNewPasswordInfo, new RecordItemIndex(14));
            repo.NewOceanAdminPortal.Reset_Password.ConfirmNewPassword.PressKeys("Password1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Login.ContinueButton' at 177;16.", repo.NewOceanAdminPortal.Login.ContinueButtonInfo, new RecordItemIndex(15));
            repo.NewOceanAdminPortal.Login.ContinueButton.Click("177;16");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
