///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Reset_Password
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ForgotPassword recording.
    /// </summary>
    [TestModule("09fcf6d7-5b96-429c-8da8-846497c2ef50", ModuleType.Recording, 1)]
    public partial class ForgotPassword : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static ForgotPassword instance = new ForgotPassword();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ForgotPassword()
        {
            Email = "shresthakarun@yahoo.com";
            SecurityAnswer = "front street";
            PasswordOne = "Password1";
            PasswordTwo = "Password1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ForgotPassword Instance
        {
            get { return instance; }
        }

#region Variables

        string _Email;

        /// <summary>
        /// Gets or sets the value of variable Email.
        /// </summary>
        [TestVariable("2bc16192-3fbe-47ea-b2a0-9c9ebc74d065")]
        public string Email
        {
            get { return _Email; }
            set { _Email = value; }
        }

        string _SecurityAnswer;

        /// <summary>
        /// Gets or sets the value of variable SecurityAnswer.
        /// </summary>
        [TestVariable("5367120c-aa03-44b4-96da-8a45d2aa77f3")]
        public string SecurityAnswer
        {
            get { return _SecurityAnswer; }
            set { _SecurityAnswer = value; }
        }

        string _PasswordOne;

        /// <summary>
        /// Gets or sets the value of variable PasswordOne.
        /// </summary>
        [TestVariable("ae548f09-a86f-4a74-9cf1-ece2279e16d3")]
        public string PasswordOne
        {
            get { return _PasswordOne; }
            set { _PasswordOne = value; }
        }

        string _PasswordTwo;

        /// <summary>
        /// Gets or sets the value of variable PasswordTwo.
        /// </summary>
        [TestVariable("92b1814c-e84e-4ad8-96b0-2391c14e8d0a")]
        public string PasswordTwo
        {
            get { return _PasswordTwo; }
            set { _PasswordTwo = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Reset_Password.Forgot' at 104;18.", repo.NewOceanAdminPortal.Reset_Password.ForgotInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Reset_Password.Forgot.Click("104;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Login.Email' at 93;16.", repo.NewOceanAdminPortal.Login.EmailInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Login.Email.Click("93;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Email' with focus on 'NewOceanAdminPortal.Login.Email'.", repo.NewOceanAdminPortal.Login.EmailInfo, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.Login.Email.PressKeys(Email);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Login.ContinueButton' at 237;14.", repo.NewOceanAdminPortal.Login.ContinueButtonInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Login.ContinueButton.Click("237;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Reset_Password.Answer' at 60;18.", repo.NewOceanAdminPortal.Reset_Password.AnswerInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Reset_Password.Answer.Click("60;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SecurityAnswer' with focus on 'NewOceanAdminPortal.Reset_Password.Answer'.", repo.NewOceanAdminPortal.Reset_Password.AnswerInfo, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.Reset_Password.Answer.PressKeys(SecurityAnswer);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Reset_Password.NewPassword' at 60;26.", repo.NewOceanAdminPortal.Reset_Password.NewPasswordInfo, new RecordItemIndex(6));
            repo.NewOceanAdminPortal.Reset_Password.NewPassword.Click("60;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PasswordOne' with focus on 'NewOceanAdminPortal.Reset_Password.NewPassword'.", repo.NewOceanAdminPortal.Reset_Password.NewPasswordInfo, new RecordItemIndex(7));
            repo.NewOceanAdminPortal.Reset_Password.NewPassword.PressKeys(PasswordOne);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Reset_Password.ConfirmNewPassword' at 45;19.", repo.NewOceanAdminPortal.Reset_Password.ConfirmNewPasswordInfo, new RecordItemIndex(8));
            repo.NewOceanAdminPortal.Reset_Password.ConfirmNewPassword.Click("45;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PasswordTwo' with focus on 'NewOceanAdminPortal.Reset_Password.ConfirmNewPassword'.", repo.NewOceanAdminPortal.Reset_Password.ConfirmNewPasswordInfo, new RecordItemIndex(9));
            repo.NewOceanAdminPortal.Reset_Password.ConfirmNewPassword.PressKeys(PasswordTwo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Reset_Password.ChangePasswordBtn' at 174;18.", repo.NewOceanAdminPortal.Reset_Password.ChangePasswordBtnInfo, new RecordItemIndex(10));
            repo.NewOceanAdminPortal.Reset_Password.ChangePasswordBtn.Click("174;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=' Your password has been changed. You can now login.') on item 'NewOceanAdminPortal.Reset_Password.DivTagYourPasswordHasBeenChangedY'.", repo.NewOceanAdminPortal.Reset_Password.DivTagYourPasswordHasBeenChangedYInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.NewOceanAdminPortal.Reset_Password.DivTagYourPasswordHasBeenChangedYInfo, "InnerText", " Your password has been changed. You can now login.");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
