///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Reset_Password
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MemSearch recording.
    /// </summary>
    [TestModule("613784b6-a107-426e-8a66-6e7dc8604146", ModuleType.Recording, 1)]
    public partial class MemSearch : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static MemSearch instance = new MemSearch();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MemSearch()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MemSearch Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Sidebar.Members' at 35;7.", repo.NewOceanAdminPortal.Sidebar.MembersInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Sidebar.Members.Click("35;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Member.SearchButton' at 63;5.", repo.NewOceanAdminPortal.Member.SearchButtonInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Member.SearchButton.Click("63;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Member.FirstName' at 88;11.", repo.NewOceanAdminPortal.Member.FirstNameInfo, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.Member.FirstName.Click("88;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'NewOceanAdminPortal.Member.FirstName'.", repo.NewOceanAdminPortal.Member.FirstNameInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Member.FirstName.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Member.SearchButton' at 27;15.", repo.NewOceanAdminPortal.Member.SearchButtonInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Member.SearchButton.Click("27;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Test') on item 'NewOceanAdminPortal.Member.Test1009'.", repo.NewOceanAdminPortal.Member.Test1009Info, new RecordItemIndex(5));
            Validate.Attribute(repo.NewOceanAdminPortal.Member.Test1009Info, "InnerText", new Regex(Regex.Escape("Test")));
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
