///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Activities
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchActivity recording.
    /// </summary>
    [TestModule("e0c1871b-495c-4b1b-aa2a-796d2b7db4b9", ModuleType.Recording, 1)]
    public partial class SearchActivity : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static SearchActivity instance = new SearchActivity();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchActivity()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchActivity Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.SearchBox' at 101;17.", repo.NewOceanAdminPortal.Activities.SearchBoxInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Activities.SearchBox.Click("101;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345 Auto' with focus on 'NewOceanAdminPortal.Activities.SearchBox'.", repo.NewOceanAdminPortal.Activities.SearchBoxInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Activities.SearchBox.PressKeys("12345 Auto");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.SpanTag12345Auto' at Center.", repo.NewOceanAdminPortal.Activities.SpanTag12345AutoInfo, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.Activities.SpanTag12345Auto.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='12345 Auto') on item 'NewOceanAdminPortal.Activities.SpanTag12345Auto'.", repo.NewOceanAdminPortal.Activities.SpanTag12345AutoInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.NewOceanAdminPortal.Activities.SpanTag12345AutoInfo, "InnerText", "12345 Auto");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
