///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Package_Group
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddChallengeTemplate recording.
    /// </summary>
    [TestModule("61a93d32-6eef-4db3-8e90-23347b47a6bf", ModuleType.Recording, 1)]
    public partial class AddChallengeTemplate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static AddChallengeTemplate instance = new AddChallengeTemplate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddChallengeTemplate()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddChallengeTemplate Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Package_Group.Challenges' at 36;7.", repo.NewOceanAdminPortal.Package_Group.ChallengesInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Package_Group.Challenges.Click("36;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}{Return}'.", new RecordItemIndex(1));
            Keyboard.Press("{Tab}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(2));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Package_Group.NewChallengeSelect' at 175;17.", repo.NewOceanAdminPortal.Package_Group.NewChallengeSelectInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Package_Group.NewChallengeSelect.Click("175;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'p' with focus on 'NewOceanAdminPortal.Package_Group.NewChallengeSelect'.", repo.NewOceanAdminPortal.Package_Group.NewChallengeSelectInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Package_Group.NewChallengeSelect.PressKeys("p");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'NewOceanAdminPortal.Package_Group.NewChallengeSelect'.", repo.NewOceanAdminPortal.Package_Group.NewChallengeSelectInfo, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.Package_Group.NewChallengeSelect.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Package_Group.NewChallengeOkayButton' at 23;18.", repo.NewOceanAdminPortal.Package_Group.NewChallengeOkayButtonInfo, new RecordItemIndex(6));
            repo.NewOceanAdminPortal.Package_Group.NewChallengeOkayButton.Click("23;18");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
