///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Package_Group
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeletePackageGroup recording.
    /// </summary>
    [TestModule("87bb370a-ea6f-496f-ab97-f0b2c7a8162e", ModuleType.Recording, 1)]
    public partial class DeletePackageGroup : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static DeletePackageGroup instance = new DeletePackageGroup();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeletePackageGroup()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeletePackageGroup Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Users.Actions' at 44;16.", repo.NewOceanAdminPortal.Users.ActionsInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Users.Actions.Click("44;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Users.Delete' at 64;10.", repo.NewOceanAdminPortal.Users.DeleteInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Users.Delete.Click("64;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImagesObject' at .485;.444.", repo.ImagesObjectInfo, new RecordItemIndex(3));
            repo.ImagesObject.Click(new Location(ImagesObject_YesToDeleteButton, ".485;.444", ImagesObject_YesToDeleteButton_Options));
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=' The Package Group has been successfully deleted.') on item 'NewOceanAdminPortal.Validations.DeletePackageValidation'.", repo.NewOceanAdminPortal.Validations.DeletePackageValidationInfo, new RecordItemIndex(4));
                Validate.Attribute(repo.NewOceanAdminPortal.Validations.DeletePackageValidationInfo, "InnerText", " The Package Group has been successfully deleted.", Validate.DefaultMessage, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
        }

#region Image Feature Data
        CompressedImage ImagesObject_YesToDeleteButton
        { get { return repo.ImagesObjectInfo.GetYesToDeleteButton(new Rectangle(295, 76, 33, 27)); } }

        Imaging.FindOptions ImagesObject_YesToDeleteButton_Options
        { get { return Imaging.FindOptions.Parse("0.8;None;0,0,0,0;True;10000000;3000ms"); } }

#endregion
    }
#pragma warning restore 0436
}
