///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Package_Group
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchPackageGroup recording.
    /// </summary>
    [TestModule("18aa87cd-9c85-4f5b-b857-5e70d566ae16", ModuleType.Recording, 1)]
    public partial class SearchPackageGroup : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static SearchPackageGroup instance = new SearchPackageGroup();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchPackageGroup()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchPackageGroup Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.SearchBox' at 53;16.", repo.NewOceanAdminPortal.Activities.SearchBoxInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Activities.SearchBox.Click("53;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AH' with focus on 'NewOceanAdminPortal.Activities.SearchBox'.", repo.NewOceanAdminPortal.Activities.SearchBoxInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Activities.SearchBox.PressKeys("AH");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}{Return}'.", new RecordItemIndex(3));
            Keyboard.Press("{Tab}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 7s.", new RecordItemIndex(4));
            Delay.Duration(7000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (TagValue>'AH') on item 'NewOceanAdminPortal.Other.Name'.", repo.NewOceanAdminPortal.Other.NameInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.NewOceanAdminPortal.Other.NameInfo, "TagValue", new Regex(Regex.Escape("AH")));
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
