///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Focuses
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FocusTagImageClick recording.
    /// </summary>
    [TestModule("0e3629a8-5ef0-48d1-9a74-1e7ace02ee0f", ModuleType.Recording, 1)]
    public partial class FocusTagImageClick : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static FocusTagImageClick instance = new FocusTagImageClick();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FocusTagImageClick()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FocusTagImageClick Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.SystemComObject.ImageFocus' at 4;4.", repo.NewOceanAdminPortal.SystemComObject.ImageFocusInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.SystemComObject.ImageFocus.Click(new Location(ImageFocus_Screenshot1, "4;4", ImageFocus_Screenshot1_Options));
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage ImageFocus_Screenshot1
        { get { return repo.NewOceanAdminPortal.SystemComObject.ImageFocusInfo.GetScreenshot1(new Rectangle(4, 4, 8, 8)); } }

        Imaging.FindOptions ImageFocus_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
