///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Validations
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidationAlert recording.
    /// </summary>
    [TestModule("31816a32-d8f3-400e-b0d9-8ea1a919452d", ModuleType.Recording, 1)]
    public partial class ValidationAlert : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static ValidationAlert instance = new ValidationAlert();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidationAlert()
        {
            varAlertText = " Please enter at least one ";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidationAlert Instance
        {
            get { return instance; }
        }

#region Variables

        string _varAlertText;

        /// <summary>
        /// Gets or sets the value of variable varAlertText.
        /// </summary>
        [TestVariable("ba9f640d-51c3-4f25-a2a7-7078b938b924")]
        public string varAlertText
        {
            get { return _varAlertText; }
            set { _varAlertText = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$varAlertText) on item 'NewOceanAdminPortal.Alert'.", repo.NewOceanAdminPortal.AlertInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.NewOceanAdminPortal.AlertInfo, "InnerText", new Regex(Regex.Escape(varAlertText)));
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
