///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Programs.Elective
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ElectiveProgramDetails recording.
    /// </summary>
    [TestModule("f2c69de6-3cc5-424d-9997-ca20177b54f6", ModuleType.Recording, 1)]
    public partial class ElectiveProgramDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSMOKTEST.SMOKTEST_SKRepository repository.
        /// </summary>
        public static CCHSSMOKTEST.SMOKTEST_SKRepository repo = CCHSSMOKTEST.SMOKTEST_SKRepository.Instance;

        static ElectiveProgramDetails instance = new ElectiveProgramDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ElectiveProgramDetails()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ElectiveProgramDetails Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '0' on item 'LoginCCHSPortal.Forms.SomeDivTag.ALevelIsRequired'.", repo.LoginCCHSPortal.Forms.SomeDivTag.ALevelIsRequiredInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Forms.SomeDivTag.ALevelIsRequired.Element.SetAttributeValue("TagValue", "0");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.ABasicScienceIsRequired' at 513;16.", repo.LoginCCHSPortal.Forms.SomeDivTag.ABasicScienceIsRequiredInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Forms.SomeDivTag.ABasicScienceIsRequired.Click("513;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}' with focus on 'LoginCCHSPortal.Forms.SomeDivTag.ABasicScienceIsRequired'.", repo.LoginCCHSPortal.Forms.SomeDivTag.ABasicScienceIsRequiredInfo, new RecordItemIndex(2));
            repo.LoginCCHSPortal.Forms.SomeDivTag.ABasicScienceIsRequired.PressKeys("{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'LoginCCHSPortal.Forms.SomeDivTag.ABasicScienceIsRequired'.", repo.LoginCCHSPortal.Forms.SomeDivTag.ABasicScienceIsRequiredInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Forms.SomeDivTag.ABasicScienceIsRequired.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.ViewArticle' at 48;13.", repo.LoginCCHSPortal.Forms.SomeDivTag.ViewArticleInfo, new RecordItemIndex(4));
            repo.LoginCCHSPortal.Forms.SomeDivTag.ViewArticle.Click("48;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Basic Science') on item 'LoginCCHSPortal.BasicScience'.", repo.LoginCCHSPortal.BasicScienceInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.LoginCCHSPortal.BasicScienceInfo, "InnerText", "Basic Science");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.ViewArticle' at 52;12.", repo.LoginCCHSPortal.Forms.SomeDivTag.ViewArticleInfo, new RecordItemIndex(6));
            repo.LoginCCHSPortal.Forms.SomeDivTag.ViewArticle.Click("52;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.FormName' at 101;20.", repo.LoginCCHSPortal.Forms.FormNameInfo, new RecordItemIndex(7));
            repo.LoginCCHSPortal.Forms.FormName.Click("101;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'LoginCCHSPortal.Forms.FormName'.", repo.LoginCCHSPortal.Forms.FormNameInfo, new RecordItemIndex(8));
            repo.LoginCCHSPortal.Forms.FormName.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '1' on item 'LoginCCHSPortal.Forms.SomeDivTag.ADurationUnitIsRequired'.", repo.LoginCCHSPortal.Forms.SomeDivTag.ADurationUnitIsRequiredInfo, new RecordItemIndex(9));
            repo.LoginCCHSPortal.Forms.SomeDivTag.ADurationUnitIsRequired.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
