///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSMOKTEST
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddNewRole recording.
    /// </summary>
    [TestModule("fda1c1d0-7080-4afb-9570-a30f9e99d44a", ModuleType.Recording, 1)]
    public partial class AddNewRole : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SMOKTEST_SKRepository repository.
        /// </summary>
        public static SMOKTEST_SKRepository repo = SMOKTEST_SKRepository.Instance;

        static AddNewRole instance = new AddNewRole();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddNewRole()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddNewRole Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Role.Roles_Menu_Item' at 53;4.", repo.LoginCCHSPortal.Role.Roles_Menu_ItemInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Role.Roles_Menu_Item.Click("53;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.New_Role_button' at 29;18.", repo.LoginCCHSPortal.Forms.SomeDivTag.New_Role_buttonInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Forms.SomeDivTag.New_Role_button.Click("29;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test Role'.", new RecordItemIndex(2));
            Keyboard.Press("Test Role");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Role.User_Search_Permisiion' at 6;8.", repo.LoginCCHSPortal.Role.User_Search_PermisiionInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Role.User_Search_Permisiion.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Role.User_Administration_Permisiion' at 8;7.", repo.LoginCCHSPortal.Role.User_Administration_PermisiionInfo, new RecordItemIndex(4));
            repo.LoginCCHSPortal.Role.User_Administration_Permisiion.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Role.User_Reset_Permisiion' at 5;8.", repo.LoginCCHSPortal.Role.User_Reset_PermisiionInfo, new RecordItemIndex(5));
            repo.LoginCCHSPortal.Role.User_Reset_Permisiion.Click("5;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Role.Member_Search_Permission' at 8;10.", repo.LoginCCHSPortal.Role.Member_Search_PermissionInfo, new RecordItemIndex(6));
            repo.LoginCCHSPortal.Role.Member_Search_Permission.Click("8;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Role.Member_Administration__Permission' at 10;2.", repo.LoginCCHSPortal.Role.Member_Administration__PermissionInfo, new RecordItemIndex(7));
            repo.LoginCCHSPortal.Role.Member_Administration__Permission.Click("10;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Save_button' at 34;18.", repo.LoginCCHSPortal.Member_Demographics.Save_buttonInfo, new RecordItemIndex(8));
            repo.LoginCCHSPortal.Member_Demographics.Save_button.Click("34;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LoginCCHSPortal.Create_Member.ToastToastSuccess'.", repo.LoginCCHSPortal.Create_Member.ToastToastSuccessInfo, new RecordItemIndex(9));
            Validate.Exists(repo.LoginCCHSPortal.Create_Member.ToastToastSuccessInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
