///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSMOKTEST
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InactiveCarePlan recording.
    /// </summary>
    [TestModule("d34d4ee2-a4f9-40d8-bc6e-75dedb503b62", ModuleType.Recording, 1)]
    public partial class InactiveCarePlan : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SMOKTEST_SKRepository repository.
        /// </summary>
        public static SMOKTEST_SKRepository repo = SMOKTEST_SKRepository.Instance;

        static InactiveCarePlan instance = new InactiveCarePlan();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InactiveCarePlan()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InactiveCarePlan Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Actions_Buttons_On_Program_' at 4;5.", repo.LoginCCHSPortal.Forms.SomeDivTag.Actions_Buttons_On_Program_Info, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Actions_Buttons_On_Program_.Click("4;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Edit_Program' at 52;9.", repo.LoginCCHSPortal.Edit_ProgramInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Edit_Program.Click("52;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.ActiveYes_' at 27;17.", repo.LoginCCHSPortal.Forms.SomeDivTag.ActiveYes_Info, new RecordItemIndex(2));
            repo.LoginCCHSPortal.Forms.SomeDivTag.ActiveYes_.Click("27;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Save_button' at 36;23.", repo.LoginCCHSPortal.Member_Demographics.Save_buttonInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Member_Demographics.Save_button.Click("36;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LoginCCHSPortal.Create_Member.ToastToastSuccess'.", repo.LoginCCHSPortal.Create_Member.ToastToastSuccessInfo, new RecordItemIndex(4));
            Validate.Exists(repo.LoginCCHSPortal.Create_Member.ToastToastSuccessInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
