///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSMOKTEST
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MemberSearchLN recording.
    /// </summary>
    [TestModule("c0f877a0-fcb1-4535-88f7-6229094a37c2", ModuleType.Recording, 1)]
    public partial class MemberSearchLN : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SMOKTEST_SKRepository repository.
        /// </summary>
        public static SMOKTEST_SKRepository repo = SMOKTEST_SKRepository.Instance;

        static MemberSearchLN instance = new MemberSearchLN();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MemberSearchLN()
        {
            SearchLN = "Smit";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MemberSearchLN Instance
        {
            get { return instance; }
        }

#region Variables

        string _SearchLN;

        /// <summary>
        /// Gets or sets the value of variable SearchLN.
        /// </summary>
        [TestVariable("c54fe2c6-9479-4f18-92d9-0307ec17574f")]
        public string SearchLN
        {
            get { return _SearchLN; }
            set { _SearchLN = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName' at 70;18.", repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstNameInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName.Click("70;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName' at 130;22.", repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstNameInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName.Click("130;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName'.", repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstNameInfo, new RecordItemIndex(2));
            repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName'.", repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstNameInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Member_Demographics.Search_Ln.FirstName.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Search_Ln.LastName' at 65;15.", repo.LoginCCHSPortal.Member_Demographics.Search_Ln.LastNameInfo, new RecordItemIndex(4));
            repo.LoginCCHSPortal.Member_Demographics.Search_Ln.LastName.Click("65;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SearchLN' with focus on 'LoginCCHSPortal.Member_Demographics.Search_Ln.LastName'.", repo.LoginCCHSPortal.Member_Demographics.Search_Ln.LastNameInfo, new RecordItemIndex(5));
            repo.LoginCCHSPortal.Member_Demographics.Search_Ln.LastName.PressKeys(SearchLN);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Search_Fn.Search_Button' at CenterLeft.", repo.LoginCCHSPortal.Member_Demographics.Search_Fn.Search_ButtonInfo, new RecordItemIndex(6));
            repo.LoginCCHSPortal.Member_Demographics.Search_Fn.Search_Button.Click(Location.CenterLeft);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LoginCCHSPortal.Member_Demographics.Search_Ln.Validation_for_LN_Smit'.", repo.LoginCCHSPortal.Member_Demographics.Search_Ln.Validation_for_LN_SmitInfo, new RecordItemIndex(7));
            Validate.Exists(repo.LoginCCHSPortal.Member_Demographics.Search_Ln.Validation_for_LN_SmitInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
