///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSMOKTEST
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NewEleciveProgram recording.
    /// </summary>
    [TestModule("747c4d65-8c6d-4521-9e7d-56024ca7e9af", ModuleType.Recording, 1)]
    public partial class NewEleciveProgram : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SMOKTEST_SKRepository repository.
        /// </summary>
        public static SMOKTEST_SKRepository repo = SMOKTEST_SKRepository.Instance;

        static NewEleciveProgram instance = new NewEleciveProgram();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NewEleciveProgram()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NewEleciveProgram Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Create_Member.New_Button' at 45;27.", repo.LoginCCHSPortal.Create_Member.New_ButtonInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Create_Member.New_Button.Click("45;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Program_Active_Yes_button' at 28;10.", repo.LoginCCHSPortal.Forms.SomeDivTag.Program_Active_Yes_buttonInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Program_Active_Yes_button.Click("28;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Globle_Icon_Program_Title' at 5;11.", repo.LoginCCHSPortal.Forms.SomeDivTag.Globle_Icon_Program_TitleInfo, new RecordItemIndex(2));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Globle_Icon_Program_Title.Click("5;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Title_English' at 37;32.", repo.LoginCCHSPortal.Health_Trackers.Title_EnglishInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Health_Trackers.Title_English.Click("37;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA Automation' with focus on 'LoginCCHSPortal.Health_Trackers.Title_English'.", repo.LoginCCHSPortal.Health_Trackers.Title_EnglishInfo, new RecordItemIndex(4));
            repo.LoginCCHSPortal.Health_Trackers.Title_English.PressKeys("QA Automation");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Title_Spanish' at 145;16.", repo.LoginCCHSPortal.Health_Trackers.Title_SpanishInfo, new RecordItemIndex(5));
            repo.LoginCCHSPortal.Health_Trackers.Title_Spanish.Click("145;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA Automation' with focus on 'LoginCCHSPortal.Health_Trackers.Title_Spanish'.", repo.LoginCCHSPortal.Health_Trackers.Title_SpanishInfo, new RecordItemIndex(6));
            repo.LoginCCHSPortal.Health_Trackers.Title_Spanish.PressKeys("QA Automation");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_Description' at 8;5.", repo.LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_DescriptionInfo, new RecordItemIndex(7));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_Description.Click("8;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA' with focus on 'LoginCCHSPortal.Health_Trackers.English_Description'.", repo.LoginCCHSPortal.Health_Trackers.English_DescriptionInfo, new RecordItemIndex(8));
            repo.LoginCCHSPortal.Health_Trackers.English_Description.PressKeys("QA");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Spanish_Description' at 61;26.", repo.LoginCCHSPortal.Health_Trackers.Spanish_DescriptionInfo, new RecordItemIndex(9));
            repo.LoginCCHSPortal.Health_Trackers.Spanish_Description.Click("61;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA' with focus on 'LoginCCHSPortal.Health_Trackers.Spanish_Description'.", repo.LoginCCHSPortal.Health_Trackers.Spanish_DescriptionInfo, new RecordItemIndex(10));
            repo.LoginCCHSPortal.Health_Trackers.Spanish_Description.PressKeys("QA");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_Description' at 7;7.", repo.LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_DescriptionInfo, new RecordItemIndex(11));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Globe_Icon_Program_Description.Click("7;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'program_icon_bicep.png' on item 'LoginCCHSPortal.Health_Trackers.Select_Icon_Field'.", repo.LoginCCHSPortal.Health_Trackers.Select_Icon_FieldInfo, new RecordItemIndex(12));
            repo.LoginCCHSPortal.Health_Trackers.Select_Icon_Field.Element.SetAttributeValue("TagValue", "program_icon_bicep.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'completed_program_icon_bicep.png' on item 'LoginCCHSPortal.CompletedIcon_Field'.", repo.LoginCCHSPortal.CompletedIcon_FieldInfo, new RecordItemIndex(13));
            repo.LoginCCHSPortal.CompletedIcon_Field.Element.SetAttributeValue("TagValue", "completed_program_icon_bicep.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'E1564B' on item 'LoginCCHSPortal.HeaderColor'.", repo.LoginCCHSPortal.HeaderColorInfo, new RecordItemIndex(14));
            repo.LoginCCHSPortal.HeaderColor.Element.SetAttributeValue("TagValue", "E1564B");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '979797' on item 'LoginCCHSPortal.CompletedHeaderColor'.", repo.LoginCCHSPortal.CompletedHeaderColorInfo, new RecordItemIndex(15));
            repo.LoginCCHSPortal.CompletedHeaderColor.Element.SetAttributeValue("TagValue", "979797");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '0' on item 'LoginCCHSPortal.Forms.SomeDivTag.Select_Program_Type_'.", repo.LoginCCHSPortal.Forms.SomeDivTag.Select_Program_Type_Info, new RecordItemIndex(16));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Select_Program_Type_.Element.SetAttributeValue("TagValue", "0");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Search_For_Activity_Dragged_' at 91;23.", repo.LoginCCHSPortal.Search_For_Activity_Dragged_Info, new RecordItemIndex(17));
            repo.LoginCCHSPortal.Search_For_Activity_Dragged_.Click("91;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Blood Sugar' with focus on 'LoginCCHSPortal.Search_For_Activity_Dragged_'.", repo.LoginCCHSPortal.Search_For_Activity_Dragged_Info, new RecordItemIndex(18));
            repo.LoginCCHSPortal.Search_For_Activity_Dragged_.PressKeys("Blood Sugar");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LoginCCHSPortal.ScheduleActivityItemUiDraggable' at 300;23.", repo.LoginCCHSPortal.ScheduleActivityItemUiDraggableInfo, new RecordItemIndex(19));
            repo.LoginCCHSPortal.ScheduleActivityItemUiDraggable.MoveTo("300;23", 800);
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginCCHSPortal.Forms.SomeDivTag.Drag_New_items_here' at Center.", repo.LoginCCHSPortal.Forms.SomeDivTag.Drag_New_items_hereInfo, new RecordItemIndex(20));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Drag_New_items_here.MoveTo(800);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'LoginCCHSPortal.Forms.SomeDivTag.Drag_New_items_here' at Center.", repo.LoginCCHSPortal.Forms.SomeDivTag.Drag_New_items_hereInfo, new RecordItemIndex(21));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Drag_New_items_here.MoveTo(800);
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Actions_on_Program_' at 1;5.", repo.LoginCCHSPortal.Actions_on_Program_Info, new RecordItemIndex(22));
            repo.LoginCCHSPortal.Actions_on_Program_.Click("1;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.FrequencyOption_Schedule_activity' at 5;3.", repo.LoginCCHSPortal.FrequencyOption_Schedule_activityInfo, new RecordItemIndex(23));
            repo.LoginCCHSPortal.FrequencyOption_Schedule_activity.Click("5;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Close_button' at 14;10.", repo.LoginCCHSPortal.Close_buttonInfo, new RecordItemIndex(24));
            repo.LoginCCHSPortal.Close_button.Click("14;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.ModalClose_button' at 23;15.", repo.LoginCCHSPortal.ModalClose_buttonInfo, new RecordItemIndex(25));
            repo.LoginCCHSPortal.ModalClose_button.Click("23;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Edit_Button_' at 3;15.", repo.LoginCCHSPortal.Forms.SomeDivTag.Edit_Button_Info, new RecordItemIndex(26));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Edit_Button_.Click("3;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Forms.SomeDivTag.Edit_Button_on_scheduled_activity' at 86;12.", repo.LoginCCHSPortal.Forms.SomeDivTag.Edit_Button_on_scheduled_activityInfo, new RecordItemIndex(27));
            repo.LoginCCHSPortal.Forms.SomeDivTag.Edit_Button_on_scheduled_activity.Click("86;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Globe_Icon_Programactivity_action' at 8;4.", repo.LoginCCHSPortal.Globe_Icon_Programactivity_actionInfo, new RecordItemIndex(28));
            repo.LoginCCHSPortal.Globe_Icon_Programactivity_action.Click("8;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Title_English' at 47;24.", repo.LoginCCHSPortal.Health_Trackers.Title_EnglishInfo, new RecordItemIndex(29));
            repo.LoginCCHSPortal.Health_Trackers.Title_English.Click("47;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA' with focus on 'LoginCCHSPortal.Health_Trackers.Title_English'.", repo.LoginCCHSPortal.Health_Trackers.Title_EnglishInfo, new RecordItemIndex(30));
            repo.LoginCCHSPortal.Health_Trackers.Title_English.PressKeys("QA");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Health_Trackers.Title_Spanish' at 39;21.", repo.LoginCCHSPortal.Health_Trackers.Title_SpanishInfo, new RecordItemIndex(31));
            repo.LoginCCHSPortal.Health_Trackers.Title_Spanish.Click("39;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'QA' with focus on 'LoginCCHSPortal.Health_Trackers.Title_Spanish'.", repo.LoginCCHSPortal.Health_Trackers.Title_SpanishInfo, new RecordItemIndex(32));
            repo.LoginCCHSPortal.Health_Trackers.Title_Spanish.PressKeys("QA");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
