///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.CodeModules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("25f1422e-db20-4f01-b2c5-ee1e768b1e2d", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            LoginEmail = "shresthakarun@yahoo.com";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _LoginEmail;

        /// <summary>
        /// Gets or sets the value of variable LoginEmail.
        /// </summary>
        [TestVariable("4cda96b2-09c9-440f-a5ec-489945f80ae8")]
        public string LoginEmail
        {
            get { return _LoginEmail; }
            set { _LoginEmail = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            DoDelay();
            Delay.Milliseconds(0);
            
            Mouse_Click_Email(repo.LoginCCHSPortal.Login.EmailInfo);
            Delay.Milliseconds(0);
            
            Key_Sequence_Email(repo.LoginCCHSPortal.Login.EmailInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_Password(repo.LoginCCHSPortal.Login.PasswordInfo);
            Delay.Milliseconds(0);
            
            Key_Sequence_Password(repo.LoginCCHSPortal.Login.PasswordInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_LoginBtn(repo.LoginCCHSPortal.Login.LoginBtnInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
