///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Members
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditMemberMiddleName recording.
    /// </summary>
    [TestModule("296cda97-79a7-48b2-90dd-ab5f2ad25a1f", ModuleType.Recording, 1)]
    public partial class EditMemberMiddleName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSMOKTEST.SMOKTEST_SKRepository repository.
        /// </summary>
        public static CCHSSMOKTEST.SMOKTEST_SKRepository repo = CCHSSMOKTEST.SMOKTEST_SKRepository.Instance;

        static EditMemberMiddleName instance = new EditMemberMiddleName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditMemberMiddleName()
        {
            MiddleNameText = "myMiddleName";
            MiddleNameNum = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditMemberMiddleName Instance
        {
            get { return instance; }
        }

#region Variables

        string _MiddleNameText;

        /// <summary>
        /// Gets or sets the value of variable MiddleNameText.
        /// </summary>
        [TestVariable("5b85c4c3-3048-422a-b3d6-5050d18babcc")]
        public string MiddleNameText
        {
            get { return _MiddleNameText; }
            set { _MiddleNameText = value; }
        }

        string _MiddleNameNum;

        /// <summary>
        /// Gets or sets the value of variable MiddleNameNum.
        /// </summary>
        [TestVariable("761154b5-0c6f-4d27-b546-76a3783f4e32")]
        public string MiddleNameNum
        {
            get { return _MiddleNameNum; }
            set { _MiddleNameNum = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.ClickOnFirstFNLN_On_Homescreen' at CenterLeft.", repo.LoginCCHSPortal.Member_Demographics.ClickOnFirstFNLN_On_HomescreenInfo, new RecordItemIndex(0));
            repo.LoginCCHSPortal.Member_Demographics.ClickOnFirstFNLN_On_Homescreen.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.MiddleName' at 181;16.", repo.LoginCCHSPortal.Member_Demographics.MiddleNameInfo, new RecordItemIndex(1));
            repo.LoginCCHSPortal.Member_Demographics.MiddleName.Click("181;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'LoginCCHSPortal.Member_Demographics.MiddleName'.", repo.LoginCCHSPortal.Member_Demographics.MiddleNameInfo, new RecordItemIndex(2));
            Keyboard.PrepareFocus(repo.LoginCCHSPortal.Member_Demographics.MiddleName);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'LoginCCHSPortal.Member_Demographics.MiddleName'.", repo.LoginCCHSPortal.Member_Demographics.MiddleNameInfo, new RecordItemIndex(3));
            repo.LoginCCHSPortal.Member_Demographics.MiddleName.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$MiddleNameText' with focus on 'LoginCCHSPortal.Member_Demographics.MiddleName'.", repo.LoginCCHSPortal.Member_Demographics.MiddleNameInfo, new RecordItemIndex(4));
            repo.LoginCCHSPortal.Member_Demographics.MiddleName.PressKeys(MiddleNameText);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$MiddleNameNum' with focus on 'LoginCCHSPortal.Member_Demographics.MiddleName'.", repo.LoginCCHSPortal.Member_Demographics.MiddleNameInfo, new RecordItemIndex(5));
            repo.LoginCCHSPortal.Member_Demographics.MiddleName.PressKeys(MiddleNameNum);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(6));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginCCHSPortal.Member_Demographics.Save_button' at 30;25.", repo.LoginCCHSPortal.Member_Demographics.Save_buttonInfo, new RecordItemIndex(7));
            repo.LoginCCHSPortal.Member_Demographics.Save_button.Click("30;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=' The changes have been successfully saved.') on item 'LoginCCHSPortal.Forms.Toast_Message'.", repo.LoginCCHSPortal.Forms.Toast_MessageInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.LoginCCHSPortal.Forms.Toast_MessageInfo, "InnerText", " The changes have been successfully saved.");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
