///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.Search
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchRewardGroupTemplate recording.
    /// </summary>
    [TestModule("fa6da18e-442c-4bfd-bbf8-37ea90f20e1a", ModuleType.Recording, 1)]
    public partial class SearchRewardGroupTemplate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static SearchRewardGroupTemplate instance = new SearchRewardGroupTemplate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchRewardGroupTemplate()
        {
            varEnterRewardToSearch = "Burn to Earn";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchRewardGroupTemplate Instance
        {
            get { return instance; }
        }

#region Variables

        string _varEnterRewardToSearch;

        /// <summary>
        /// Gets or sets the value of variable varEnterRewardToSearch.
        /// </summary>
        [TestVariable("f1823954-ecc7-4825-a420-35880c5be1e6")]
        public string varEnterRewardToSearch
        {
            get { return _varEnterRewardToSearch; }
            set { _varEnterRewardToSearch = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Activities.SearchBox' at 53;16.", repo.NewOceanAdminPortal.Activities.SearchBoxInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Activities.SearchBox.Click("53;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varEnterRewardToSearch' with focus on 'NewOceanAdminPortal.Activities.SearchBox'.", repo.NewOceanAdminPortal.Activities.SearchBoxInfo, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Activities.SearchBox.PressKeys(varEnterRewardToSearch);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(2));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(3));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (TagValue>$varEnterRewardToSearch) on item 'NewOceanAdminPortal.Other.TemplateTitle'.", repo.NewOceanAdminPortal.Other.TemplateTitleInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.NewOceanAdminPortal.Other.TemplateTitleInfo, "TagValue", new Regex(Regex.Escape(varEnterRewardToSearch)));
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
