///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CCHSSmokeTest.Recordings.User
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditUser recording.
    /// </summary>
    [TestModule("b9c0893e-d55f-4296-b13b-83bd33b7f6ac", ModuleType.Recording, 1)]
    public partial class EditUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CCHSSmokeTest.SmokeTestRepositoryKS repository.
        /// </summary>
        public static CCHSSmokeTest.SmokeTestRepositoryKS repo = CCHSSmokeTest.SmokeTestRepositoryKS.Instance;

        static EditUser instance = new EditUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditUser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditUser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Users.ActionsCaret' at 54;8.", repo.NewOceanAdminPortal.Users.ActionsCaretInfo, new RecordItemIndex(0));
            repo.NewOceanAdminPortal.Users.ActionsCaret.Click("54;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Users.ATagUe0' at 54;3.", repo.NewOceanAdminPortal.Users.ATagUe0Info, new RecordItemIndex(1));
            repo.NewOceanAdminPortal.Users.ATagUe0.Click("54;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Member.LastName' at 167;17.", repo.NewOceanAdminPortal.Member.LastNameInfo, new RecordItemIndex(2));
            repo.NewOceanAdminPortal.Member.LastName.Click("167;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'NewOceanAdminPortal.Member.LastName'.", repo.NewOceanAdminPortal.Member.LastNameInfo, new RecordItemIndex(3));
            repo.NewOceanAdminPortal.Member.LastName.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Users.Permissions' at 78;25.", repo.NewOceanAdminPortal.Users.PermissionsInfo, new RecordItemIndex(4));
            repo.NewOceanAdminPortal.Users.Permissions.Click("78;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Users.Role19' at 4;7.", repo.NewOceanAdminPortal.Users.Role19Info, new RecordItemIndex(5));
            repo.NewOceanAdminPortal.Users.Role19.Click("4;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Users.Role20' at 1;2.", repo.NewOceanAdminPortal.Users.Role20Info, new RecordItemIndex(6));
            repo.NewOceanAdminPortal.Users.Role20.Click("1;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Member.Save' at 29;16.", repo.NewOceanAdminPortal.Member.SaveInfo, new RecordItemIndex(7));
            repo.NewOceanAdminPortal.Member.Save.Click("29;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=' The changes have been successfully saved.') on item 'NewOceanAdminPortal.Validations.DivTagTheChangesHaveBeenSuccessfull'.", repo.NewOceanAdminPortal.Validations.DivTagTheChangesHaveBeenSuccessfullInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.NewOceanAdminPortal.Validations.DivTagTheChangesHaveBeenSuccessfullInfo, "InnerText", " The changes have been successfully saved.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(9));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.Users.Actions' at 61;15.", repo.NewOceanAdminPortal.Users.ActionsInfo, new RecordItemIndex(10));
            repo.NewOceanAdminPortal.Users.Actions.Click("61;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ResetAccount' at 70;11.", repo.NewOceanAdminPortal.ResetAccountInfo, new RecordItemIndex(11));
            repo.NewOceanAdminPortal.ResetAccount.Click("70;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewOceanAdminPortal.ResetAccountYes' at 22;14.", repo.NewOceanAdminPortal.ResetAccountYesInfo, new RecordItemIndex(12));
            repo.NewOceanAdminPortal.ResetAccountYes.Click("22;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewOceanAdminPortal.DivTagTheAccountHasBeenSuccessfully'.", repo.NewOceanAdminPortal.DivTagTheAccountHasBeenSuccessfullyInfo, new RecordItemIndex(13));
            Validate.Exists(repo.NewOceanAdminPortal.DivTagTheAccountHasBeenSuccessfullyInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
